### ISSUE TITLE
Unrecognized option "pretty" under "swagger"

### ISSUE THREAD

**Issue by codeaid** [TimeIncOSS/swagger-bundle#19]
[Application Coniguration](/TimeIncOSS/swagger-bundle#application-configuration) section of `README.md` shows an invalid option `pretty`, which should be `pretty_json`.

This:

```yaml
swagger:
    # ...
    pretty: true
```

should be updated to:

```yaml
swagger:
    # ...
    pretty_json: true
```
